#!/bin/bash
source set-env.sh

set -e
set -o pipefail
set -x
orig_dir=$( pwd )

BUILD_DIR="/tmp/build"

orig_dir=$( pwd )
mkdir -p ${BUILD_DIR}
pushd ${BUILD_DIR}

echo "+ Fetching libevent sources..."
# rm -rf /app/vendor/memcached
# mkdir -p /app/vendor/memcached
mkdir -p /app/local
curl -L "https://${S3_BUCKET}.s3.amazonaws.com/php/sources/libevent-${LIBEVENT_VERSION}.tar.gz" -o - | tar xz
pushd libevent-${LIBEVENT_VERSION}
./configure --prefix=/app/local
make
make install
popd

echo "+ Fetching memcached server sources..."
rm -rf /app/vendor/memcached
mkdir -p /app/vendor/memcached
curl -L "https://${S3_BUCKET}.s3.amazonaws.com/php/sources/memcached-${MEMCACHED_VERSION}.tar.gz" -o - | tar xz
pushd memcached-${MEMCACHED_VERSION}
./configure --prefix=/app/vendor/memcached --with-libevent=/app/local
make
make install
popd

echo "+ Packaging memcached server..."
pushd /app/vendor/memcached
tar czf $orig_dir/memcached-server-${MEMCACHED_VERSION}-vr${BUILD_SUFFIX}.tar.gz *
popd

echo "+ Binaries are packaged in $orig_dir/*.tar.gz. Upload to s3 bucket of your choice."
echo "+ Done!"
