#!/bin/bash

./set-env.sh

set -e
set -o pipefail

orig_dir=$( pwd )
mkdir -p build
pushd build

echo "+ Fetching memcached server sources..."
rm -rf /app/vendor/memcached
mkdir -p /app/vendor/memcached
curl -L "https://s3.amazonaws.com/${S3_BUCKET}/memcached-server-${MEMCACHED_VERSION}.tar.gz" -o - | tar xz
pushd memcached-server-${MEMCACHED_VERSION}
./configure --prefix=/app/vendor/memcached
make
make install
popd

echo "+ Packaging memcached server..."
pushd /app/vendor/memcached
tar czf $orig_dir/memcached-server-${MEMCACHED_VERSION}-vr.tar.gz *
popd

echo "+ Binaries are packaged in $orig_dir/*.tar.gz. Upload to s3 bucket of your choice."
echo "+ Done!"
