#!/bin/bash

export S3_BUCKET="yg-php-buildpack-opi"
export LIBMCRYPT_VERSION="2.5.8"
export LIBJPEG_VERSION="9a" 
export PHP_VERSION="5.5.15"
export LIBMEMCACHED_VERSION="1.0.18"
export MEMCACHED_VERSION="2.2.0"
export MEMCACHE_VERSION="3.0.8"
export NEWRELIC_VERSION="4.10.1.62"
export RABBITMQ_VERSION="1.4.0"
export LIBRABBITMQ_VERSION="0.5.0"
export OPENSSL_VERSION="0_9_8"
export MEMCACHED_VERSION="1.4.20"